# Files that must live in the repo (.gitignore, .envrc, CI stubs, editor config)
# are owned by nullkomma: `nix run .#write-files` writes them, `checks.files` fails on drift.
{
  flake.flakeModules.default =
    { lib, self, ... }:
    {
      perSystem =
        { config, pkgs, ... }:
        let
          files = lib.filterAttrs (_: f: f.enable) config.nullkomma.files;
          banner = "Generated by nullkomma; edit flake.nix, then run `nix run .#write-files`.";
          fileModule =
            { name, config, ... }:
            {
              options = {
                enable = lib.mkOption {
                  type = lib.types.bool;
                  default = true;
                  description = "Whether to manage `${name}`.";
                };
                text = lib.mkOption {
                  type = lib.types.nullOr lib.types.lines;
                  default = null;
                  description = "File content; sets `source`.";
                };
                comment = lib.mkOption {
                  type = lib.types.nullOr lib.types.str;
                  default = "#";
                  description = "Line comment token for the generated-file banner prepended to `text`; null disables it.";
                };
                source = lib.mkOption {
                  type = lib.types.path;
                  description = "Store path whose content is written to `${name}`.";
                };
              };
              config.source = lib.mkIf (config.text != null) (
                pkgs.writeText "nullkomma-${lib.replaceStrings [ "/" ] [ "-" ] name}" (
                  lib.optionalString (config.comment != null) "${config.comment} ${banner}\n" + config.text
                )
              );
            };
        in
        {
          options.nullkomma.files = lib.mkOption {
            type = lib.types.attrsOf (lib.types.submodule fileModule);
            default = { };
            description = "Files, keyed by path relative to the repo root, that nullkomma writes and checks.";
          };
          config = {
            nullkomma.tasks.write-files = {
              description = "Write nullkomma-managed files (.gitignore, .envrc, CI stubs, …) into the repo";
              runtimeInputs = [
                pkgs.coreutils
                pkgs.git
              ];
              command = ''
                root="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
              ''
              + lib.concatStrings (
                lib.mapAttrsToList (path: f: ''
                  install -D -m 644 ${f.source} "$root"/${lib.escapeShellArg path}
                  echo "wrote ${path}"
                '') files
              );
            };
            checks = lib.mkIf (files != { }) {
              files = pkgs.runCommandLocal "nullkomma-files" { nativeBuildInputs = [ pkgs.diffutils ]; } (
                ''
                  status=0
                ''
                + lib.concatStrings (
                  lib.mapAttrsToList (
                    path: f:
                    let
                      repoFile = lib.escapeShellArg "${self}/${path}";
                    in
                    ''
                      if [ -e ${repoFile} ]; then
                        diff -u ${repoFile} ${f.source} || status=1
                      else
                        echo "nullkomma: ${path} is missing from the flake source (not written or not git-added?)" >&2
                        status=1
                      fi
                    ''
                  ) files
                )
                + ''
                  if [ "$status" -ne 0 ]; then
                    echo "nullkomma: generated files are out of date; run: nix run .#write-files" >&2
                    exit 1
                  fi
                  touch $out
                ''
              );
            };
          };
        };
    };
}
