name: Maintenance
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0" # runs weekly on Sunday at 01:00
jobs:
  nix-maintenance:
    name: Nix Maintenance
    runs-on: ubuntu-latest
    permissions:
      id-token: "write"
      contents: "write"
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v6
      - uses: DeterminateSystems/determinate-nix-action@main
      - uses: DeterminateSystems/flake-checker-action@main
      - uses: DeterminateSystems/update-flake-lock@main
        with:
          pr-title: "Update flake.lock"
          pr-labels: |
            dependencies
            automated
