name: Maintenance
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0" # runs weekly on Sunday at 01:00
jobs:
  nix-maintenance:
    name: Nix Maintenance
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          determinate: true
      - uses: DeterminateSystems/flakehub-cache-action@main
      - uses: DeterminateSystems/update-flake-lock@main
        with:
          pr-title: "Update flake.lock"
          pr-labels: |
            dependencies
            automated
      - uses: DeterminateSystems/flake-checker-action@main
        with:
          fail-mode: true
